# See: https://pnpm.io/supply-chain-security
blockExoticSubdeps: true
minimumReleaseAge: 20160 # 14 days (keep in sync with Renovate config)
minimumReleaseAgeExclude:
  # Renovate security update: axios@1.13.5
  - axios@1.13.5
